"""C22: exact planning and sampled value learning on the C21 courier model.

Exact routines may inspect the known outcome table. Sampled learners receive
only trajectories generated by the simulator; the exact table is used again
afterward only as a diagnostic reference. This is a finite teaching model.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
from pathlib import Path

from delivery_decision_lab import ACTIONS, choose, outcomes


ROOT = Path(__file__).resolve().parents[2]
STATES = (0, 1, 2)
POLICIES = ("immediate", "conserve")
CHECKPOINTS = (1, 10, 100, 500, 2000)


def action_return(energy: int, action: str, tail: dict[int, float], gamma: float = 1.0) -> float:
    """Known-model expectation for one action plus a known tail value."""
    return sum(
        probability * (reward + gamma * tail[next_energy])
        for probability, reward, next_energy in outcomes(energy, action)
    )


def finite_model(horizon: int = 3) -> dict:
    fixed: dict[str, list[dict[int, float]]] = {}
    for policy in POLICIES:
        values = [{energy: 0.0 for energy in STATES}]
        for _ in range(horizon):
            prior = values[-1]
            values.append({
                energy: action_return(energy, choose(policy, energy), prior)
                for energy in STATES
            })
        fixed[policy] = values

    optimal_values = [{energy: 0.0 for energy in STATES}]
    optimal_actions: list[dict[int, str]] = [{}]
    optimal_action_values: list[dict[int, dict[str, float]]] = [{}]
    for _ in range(horizon):
        prior = optimal_values[-1]
        candidates = {
            energy: {
                action: action_return(energy, action, prior)
                for action in ACTIONS
            }
            for energy in STATES
        }
        best_actions = {
            energy: max(ACTIONS, key=lambda action: candidates[energy][action])
            for energy in STATES
        }
        optimal_action_values.append(candidates)
        optimal_actions.append(best_actions)
        optimal_values.append({
            energy: candidates[energy][best_actions[energy]]
            for energy in STATES
        })
    return {
        "horizon": horizon,
        "fixed_policy_values_by_remaining_actions": fixed,
        "optimal_values_by_remaining_actions": optimal_values,
        "optimal_action_values_by_remaining_actions": optimal_action_values,
        "optimal_actions_by_remaining_actions": optimal_actions,
    }


def discounted_backup(
    energy: int, action: str, tail: dict[int, float], gamma: float
) -> float:
    return action_return(energy, action, tail, gamma)


def discounted_policy_value(
    policy: dict[int, str], gamma: float, tolerance: float = 1e-12
) -> tuple[dict[int, float], int, float]:
    value = {energy: 0.0 for energy in STATES}
    for iteration in range(1, 100_001):
        next_value = {
            energy: discounted_backup(energy, policy[energy], value, gamma)
            for energy in STATES
        }
        delta = max(abs(next_value[energy] - value[energy]) for energy in STATES)
        value = next_value
        if delta < tolerance:
            return value, iteration, delta
    raise RuntimeError("discounted policy evaluation did not converge")


def greedy_policy(value: dict[int, float], gamma: float) -> dict[int, str]:
    return {
        energy: max(
            ACTIONS,
            key=lambda action: discounted_backup(energy, action, value, gamma),
        )
        for energy in STATES
    }


def discounted_control(gamma: float = 0.9, tolerance: float = 1e-12) -> dict:
    if not 0.0 <= gamma < 1.0:
        raise ValueError("discount factor must be in [0,1)")
    baselines = {}
    for name in POLICIES:
        policy = {energy: choose(name, energy) for energy in STATES}
        value, steps, delta = discounted_policy_value(policy, gamma, tolerance)
        baselines[name] = {
            "policy": policy,
            "value": value,
            "evaluation_iterations": steps,
            "last_delta": delta,
        }

    value = {energy: 0.0 for energy in STATES}
    for iteration in range(1, 100_001):
        next_value = {
            energy: max(
                discounted_backup(energy, action, value, gamma)
                for action in ACTIONS
            )
            for energy in STATES
        }
        delta = max(abs(next_value[energy] - value[energy]) for energy in STATES)
        value = next_value
        if delta < tolerance:
            value_iteration_steps = iteration
            break
    else:
        raise RuntimeError("discounted value iteration did not converge")
    greedy = greedy_policy(value, gamma)

    current = baselines["immediate"]["policy"].copy()
    improvement_history = []
    for _ in range(20):
        evaluated, steps, _ = discounted_policy_value(current, gamma, tolerance)
        improved = greedy_policy(evaluated, gamma)
        improvement_history.append({
            "policy_before": current,
            "value_before": evaluated,
            "policy_after_greedy_improvement": improved,
            "evaluation_iterations": steps,
        })
        if improved == current:
            break
        current = improved
    else:
        raise RuntimeError("policy improvement did not stabilize")
    improved_value, _, _ = discounted_policy_value(current, gamma, tolerance)
    if max(abs(improved_value[s] - value[s]) for s in STATES) > 1e-8:
        raise AssertionError("policy iteration and value iteration disagree")
    return {
        "gamma": gamma,
        "baselines": baselines,
        "value_iteration": {
            "optimal_value": value,
            "greedy_policy": greedy,
            "iterations": value_iteration_steps,
            "last_delta": delta,
        },
        "policy_iteration": {
            "history": improvement_history,
            "stable_policy": current,
            "value": improved_value,
        },
    }


def sample_episode(
    policy: str | None, start: int, horizon: int, rng: random.Random
) -> list[dict]:
    """The only routine seen by learners that talks to the environment."""
    energy = start
    events = []
    for remaining in range(horizon, 0, -1):
        action = choose(policy, energy) if policy is not None else rng.choice(ACTIONS)
        draw = rng.random()
        boundary = 0.0
        for probability, reward, next_energy in outcomes(energy, action):
            boundary += probability
            if draw < boundary:
                break
        events.append({
            "remaining_actions": remaining,
            "state_before": energy,
            "action": action,
            "reward": reward,
            "state_after": next_energy,
        })
        energy = next_energy
    return events


def blank_values(horizon: int) -> dict[int, dict[int, float]]:
    return {n: {energy: 0.0 for energy in STATES} for n in range(horizon + 1)}


def blank_counts(horizon: int) -> dict[int, dict[int, int]]:
    return {n: {energy: 0 for energy in STATES} for n in range(horizon + 1)}


def update_mc(
    events: list[dict],
    values: dict[int, dict[int, float]],
    counts: dict[int, dict[int, int]],
) -> None:
    """Observed complete suffix return becomes an empirical mean target."""
    remaining_return = 0.0
    for event in reversed(events):
        remaining_return += event["reward"]
        n, energy = event["remaining_actions"], event["state_before"]
        counts[n][energy] += 1
        old = values[n][energy]
        values[n][energy] = old + (remaining_return - old) / counts[n][energy]


def update_td(
    events: list[dict],
    values: dict[int, dict[int, float]],
    counts: dict[int, dict[int, int]],
) -> None:
    """One sampled reward plus the current next-state estimate is the target."""
    for event in events:
        n, energy = event["remaining_actions"], event["state_before"]
        next_energy = event["state_after"]
        target = event["reward"] + values[n - 1][next_energy]
        counts[n][energy] += 1
        old = values[n][energy]
        values[n][energy] = old + (target - old) / counts[n][energy]


def value_snapshot(
    values: dict[int, dict[int, float]],
    counts: dict[int, dict[int, int]],
    reference: list[dict[int, float]],
    epoch: int,
) -> dict:
    return {
        "epoch": epoch,
        "episodes_seen": epoch * 9,
        "value_3_from_energy_2": values[3][2],
        "true_value_3_from_energy_2": reference[3][2],
        "max_absolute_error_on_all_n_state_pairs": max(
            abs(values[n][energy] - reference[n][energy])
            for n in (1, 2, 3) for energy in STATES
        ),
        "min_visits_on_all_n_state_pairs": min(
            counts[n][energy] for n in (1, 2, 3) for energy in STATES
        ),
    }


def sampled_policy_prediction(
    reference: list[dict[int, float]], epochs: int, seed: int
) -> dict:
    rng = random.Random(seed)
    mc, td = blank_values(3), blank_values(3)
    mc_counts, td_counts = blank_counts(3), blank_counts(3)
    checkpoints = []
    for epoch in range(1, epochs + 1):
        starts = [(energy, n) for n in (1, 2, 3) for energy in STATES]
        rng.shuffle(starts)
        for energy, n in starts:
            events = sample_episode("immediate", energy, n, rng)
            update_mc(events, mc, mc_counts)
            update_td(events, td, td_counts)
        if epoch in CHECKPOINTS or epoch == epochs:
            checkpoints.append({
                "epoch": epoch,
                "monte_carlo": value_snapshot(mc, mc_counts, reference, epoch),
                "temporal_difference": value_snapshot(td, td_counts, reference, epoch),
            })
    return {
        "policy": "immediate",
        "seed": seed,
        "epochs": epochs,
        "sampling": "each epoch resets nine episodes, one for every starting energy and remaining horizon 1/2/3; within-episode actions follow the fixed immediate policy",
        "mc_values": mc,
        "td_values": td,
        "visits": mc_counts,
        "checkpoints": checkpoints,
    }


def blank_q(horizon: int) -> dict[int, dict[int, dict[str, float]]]:
    return {
        n: {energy: {action: 0.0 for action in ACTIONS} for energy in STATES}
        for n in range(horizon + 1)
    }


def update_q(
    events: list[dict],
    q: dict[int, dict[int, dict[str, float]]],
    counts: dict[int, dict[int, dict[str, int]]],
) -> None:
    for event in events:
        n, energy, action = (
            event["remaining_actions"], event["state_before"], event["action"]
        )
        next_energy = event["state_after"]
        tail = max(q[n - 1][next_energy].values()) if n > 1 else 0.0
        target = event["reward"] + tail
        counts[n][energy][action] += 1
        old = q[n][energy][action]
        q[n][energy][action] = (
            old + (target - old) / counts[n][energy][action]
        )


def q_snapshot(
    q: dict[int, dict[int, dict[str, float]]],
    counts: dict[int, dict[int, dict[str, int]]],
    exact_q: list[dict[int, dict[str, float]]],
    epoch: int,
) -> dict:
    greedy = {
        n: {
            energy: max(ACTIONS, key=lambda action: q[n][energy][action])
            for energy in STATES
        }
        for n in (1, 2, 3)
    }
    exact_greedy = {
        n: {
            energy: max(ACTIONS, key=lambda action: exact_q[n][energy][action])
            for energy in STATES
        }
        for n in (1, 2, 3)
    }
    return {
        "epoch": epoch,
        "episodes_seen": epoch * 9,
        "q_3_energy_2": q[3][2].copy(),
        "greedy_3_energy_2": greedy[3][2],
        "greedy_matches_exact_in_9_pairs": sum(
            greedy[n][energy] == exact_greedy[n][energy]
            for n in (1, 2, 3) for energy in STATES
        ),
        "max_absolute_q_error": max(
            abs(q[n][energy][action] - exact_q[n][energy][action])
            for n in (1, 2, 3) for energy in STATES for action in ACTIONS
        ),
        "min_state_action_visits": min(
            counts[n][energy][action]
            for n in (1, 2, 3) for energy in STATES for action in ACTIONS
        ),
    }


def sampled_control(exact_q: list[dict[int, dict[str, float]]], epochs: int, seed: int) -> dict:
    rng = random.Random(seed)
    q = blank_q(3)
    counts = {
        n: {energy: {action: 0 for action in ACTIONS} for energy in STATES}
        for n in range(4)
    }
    checkpoints = []
    for epoch in range(1, epochs + 1):
        starts = [(energy, n) for n in (1, 2, 3) for energy in STATES]
        rng.shuffle(starts)
        for energy, n in starts:
            events = sample_episode(None, energy, n, rng)
            update_q(events, q, counts)
        if epoch in CHECKPOINTS or epoch == epochs:
            checkpoints.append(q_snapshot(q, counts, exact_q, epoch))
    return {
        "seed": seed,
        "epochs": epochs,
        "sampling": "each epoch resets nine episodes; at every step data collection chooses uniformly among all three actions; only sampled transitions enter Q updates",
        "q_values": q,
        "visits": counts,
        "checkpoints": checkpoints,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=20260924)
    parser.add_argument("--gamma", type=float, default=0.9)
    parser.add_argument(
        "--out", type=Path, default=Path("work/results/c22_value_learning.json")
    )
    args = parser.parse_args()
    if args.epochs <= 0:
        raise ValueError("epochs must be positive")
    if not 0.0 <= args.gamma < 1.0:
        raise ValueError("gamma must be in [0,1)")
    out = args.out if args.out.is_absolute() else ROOT / args.out
    if out.exists():
        raise FileExistsError(f"keep previous result; choose a different --out: {out}")

    finite = finite_model()
    expected = finite["fixed_policy_values_by_remaining_actions"]
    assert expected["immediate"][1][2] == 2.5
    assert expected["immediate"][2][2] == 1.5
    assert expected["immediate"][3][2] == 4.0
    assert expected["conserve"][1][2] == 2.0
    assert expected["conserve"][2][2] == 4.0
    assert expected["conserve"][3][2] == 3.0
    assert finite["optimal_values_by_remaining_actions"][2][2] == 4.0
    assert finite["optimal_values_by_remaining_actions"][3][2] == 4.0
    discounted = discounted_control(args.gamma)
    prediction = sampled_policy_prediction(expected["immediate"], args.epochs, args.seed)
    control = sampled_control(
        finite["optimal_action_values_by_remaining_actions"],
        args.epochs, args.seed + 1,
    )
    output = {
        "scope": "C21 fictional courier; exact planning with known model, sampled fixed-policy MC/TD prediction, and uniformly exploring sampled finite-horizon Q control; no physical robot, neural Q network, or language-model alignment",
        "timing": "state_t -> action_t -> (reward_{t+1}, state_{t+1})",
        "finite_horizon": finite,
        "discounted_known_model": discounted,
        "sampled_fixed_policy_prediction": prediction,
        "sampled_finite_control": control,
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    temp = out.with_name(out.name + ".tmp")
    temp.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temp, out)

    print("finite optimal n=2, state=2:", finite["optimal_values_by_remaining_actions"][2][2])
    print("finite optimal n=3, state=2:", finite["optimal_values_by_remaining_actions"][3][2])
    print("discounted optimal:", discounted["value_iteration"]["greedy_policy"])
    print("discounted value state=2:", f"{discounted['value_iteration']['optimal_value'][2]:.6f}")
    last_prediction = prediction["checkpoints"][-1]
    print(
        "sampled fixed immediate V3(2), MC/TD:",
        f"{last_prediction['monte_carlo']['value_3_from_energy_2']:.4f}",
        f"{last_prediction['temporal_difference']['value_3_from_energy_2']:.4f}",
    )
    last_control = control["checkpoints"][-1]
    print(
        "sampled Q greedy 3 steps from energy 2:",
        last_control["greedy_3_energy_2"],
        "matches:", last_control["greedy_matches_exact_in_9_pairs"], "/9",
    )


if __name__ == "__main__":
    main()
